### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by natalian98** [canonical/create-pull-request#53]
Right now we need to pin the action to main: `canonical/create-pull-request@main`
However if breaking changes are introduced, this might break workflows that use this action as well.

Would it be possible to add versions/tags for this action, like it's done for [charming-actions](https://github.com/canonical/charming-actions), for example?

**Comment by weiiwang01** [comment]
Sorry I missed this issue completely. 
Thank you for your suggestion. The goal has been to maintain backward compatibility with the `create-pull-request` action. And so far it's the case in the main branch. 
But I can say it will never happen in the future, so I have create a tag `v1`, just in case you would like a more stable release.
